import Foundation

/// An enumeration describing analytics events generated by the app.  Events
/// capture user interactions such as completing a lesson or tapping a
/// particular button.  Keeping the event definitions in a central location
/// makes it easy to audit what data is collected and to update the schema.
public enum AnalyticsEvent: Equatable {
    /// Called when a lesson is started for a given grade and topic.
    case lessonStarted(grade: String, lessonID: String)
    /// Called when a lesson is completed successfully.
    case lessonCompleted(grade: String, lessonID: String)
    /// Called when a question is answered.  The associated value tracks
    /// whether the answer was correct.
    case questionAnswered(correct: Bool)
    /// Called when a feature screen is shown.  Useful for measuring
    /// engagement.
    case screenPresented(name: String)
    /// Called when a Grade 1 unit unlocks for the first time.
    case gradeUnitUnlocked(grade: String, unitID: String)
    /// Called when the goal tracker snapshot updates.
    case gradeGoalProgressUpdated(grade: String, completedLessons: Int, totalLessons: Int)
    /// Called when a diagnostic placement check is completed.
    case diagnosticCompleted(grade: String)
    /// Called when a challenge set is surfaced in a lesson.
    case challengeSetPresented(grade: String, lessonID: String, challengeID: String)
    /// Called when remediation referencing Kindergarten content is suggested.
    case remediationSuggested(grade: String, kindergartenLessonID: String, lessonID: String)
    /// Called when a learner acknowledges a remediation prompt.
    case remediationAcknowledged(grade: String, kindergartenLessonID: String, lessonID: String)
    /// Called when the multi-grade overview on the home screen is viewed.
    case multiGradeOverviewViewed
}

/// A protocol for analytics logging.  This allows the app to collect
/// behavioural data without coupling to a specific analytics SDK.  In
/// production the implementation might forward events to a server, whereas
/// tests can substitute a mock implementation.
public protocol AnalyticsLogging {
    /// Records an analytics event.
    func log(event: AnalyticsEvent)
}

/// A no‑op analytics logger used in environments where analytics should be
/// disabled.  This is the default implementation registered in the
/// `DependencyContainer` if no other logger is provided.
public final class NoopAnalyticsLogger: AnalyticsLogging {
    public init() {}
    public func log(event: AnalyticsEvent) {
        // Intentionally left blank – avoids any side effects.
    }
}